import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { explainPathClassification, loadPathClassificationConfig } from "../src/path-classification.js";

const put = (root, file, text = "") => {
  mkdirSync(dirname(join(root, file)), { recursive: true });
  writeFileSync(join(root, file), text);
};

test("path classification explains defaults for e2e, generated, mock, stories, docs, benchmarks and temp roots", () => {
  const cases = [
    ["test-e2e/cypress/support/testLocators/a.ts", ["test", "e2e"]],
    ["src/generated/api/client.ts", ["generated"]],
    ["build/static/js/main.abc123.js", ["generated"]],
    ["src/widget/mockData.ts", ["mock"]],
    ["src/Button.stories.tsx", ["story"]],
    ["docs/architecture.md", ["docs"]],
    ["benchmarks/bench_common.py", ["benchmark"]],
    ["tools/__temp/import_pos.py", ["temp"]],
    ["test.py", ["test"]],
  ];
  for (const [path, expected] of cases) {
    const info = explainPathClassification(null, path, { content: "" });
    for (const category of expected) assert.ok(info.classes.includes(category), `${path} is ${category}`);
    assert.ok(info.matchedRule?.pattern, `${path} discloses its matched rule`);
  }
});

test(".weavatrix.json adds bounded classifications/excludes without acting like hard ignore", () => {
  const repo = mkdtempSync(join(tmpdir(), "weavatrix-classify-"));
  try {
    put(repo, ".weavatrix.json", JSON.stringify({
      classify: { generated: ["vendor-api/**"], story: "visual-cases/**", product: ["benchmarks/product/**"] },
      exclude: ["scratch/**"],
      ignoredUnknownKey: ["**/*"],
    }));
    put(repo, ".weavatrixignore", "src/ignored.ts\n");
    put(repo, "vendor-api/client.ts", "export const client = 1;\n");
    put(repo, "scratch/probe.ts", "export const probe = 1;\n");
    put(repo, "src/ignored.ts", "export const stillClassifiable = 1;\n");

    const generated = explainPathClassification(repo, "vendor-api/client.ts", { content: "" });
    assert.ok(generated.classes.includes("generated"));
    assert.deepEqual(generated.matchedRule, { category: "generated", source: "config", pattern: "vendor-api/**" });
    const excluded = explainPathClassification(repo, "scratch/probe.ts", { content: "" });
    assert.equal(excluded.excluded, true);
    assert.ok(excluded.matchedRules.some((rule) => rule.category === "exclude" && rule.pattern === "scratch/**"));
    const hardIgnored = explainPathClassification(repo, "src/ignored.ts", { content: "" });
    assert.deepEqual(hardIgnored.classes, [], ".weavatrixignore remains a separate hard-index boundary");
    assert.equal(hardIgnored.excluded, false);
    const ordinaryBenchmark = explainPathClassification(repo, "benchmarks/bench_common.py", { content: "" });
    assert.ok(ordinaryBenchmark.classes.includes("benchmark"));
    const productBenchmark = explainPathClassification(repo, "benchmarks/product/core.py", { content: "" });
    assert.equal(productBenchmark.productOverride, true);
    assert.ok(!productBenchmark.classes.includes("benchmark"), "classify.product opts verified benchmark source back into production review");
    assert.deepEqual(productBenchmark.matchedRule, { category: "product", source: "config", pattern: "benchmarks/product/**" });
  } finally { rmSync(repo, { recursive: true, force: true }); }
});

test("generated-file headers are recognized and oversized config is refused", () => {
  const repo = mkdtempSync(join(tmpdir(), "weavatrix-classify-header-"));
  try {
    put(repo, "src/client.ts", "// Code generated by OpenAPI Generator. DO NOT EDIT.\nexport const api = 1;\n");
    assert.ok(explainPathClassification(repo, "src/client.ts").classes.includes("generated"));
    put(repo, ".weavatrix.json", JSON.stringify({ classify: { test: ["x".repeat(70 * 1024)] } }));
    assert.equal(loadPathClassificationConfig(repo).error, "config-too-large");
  } finally { rmSync(repo, { recursive: true, force: true }); }
});
